tap "homebrew/cask-fonts"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "koekeishiya/formulae"

cask_args appdir: "/Applications"

brew "coreutils"
brew "diffutils"
brew "direnv"
brew "findutils"
brew "zsh"
brew "zsh-completions"
brew "fzf"
brew "git"
brew "gnu-sed"
brew "gnu-tar"
brew "gnu-time"
brew "grep"
brew "jq"
brew "jless"
brew "yq"
brew "fd"
brew "mas"
brew "python"
brew "golang"
brew "rename"
brew "rsync"
# brew "starship"
brew "tree"
brew "vim"
brew "helix"
brew "wget"
brew "tldr"
brew "noti"
brew "eza"
brew "zoxide"
brew "hyperkey"
brew "ydiff"
brew "git-delta"

# Work
brew "krew"
brew "kubernetes-cli"
brew "kubectx"
brew "kustomize"
brew "stern"
brew "eksctl"
brew "kind"
brew "cosign"
brew "k9s"
brew "viddy"
brew "colima"
brew "gh"
brew "kubeval"
brew "kdash"

# brew "koekeishiya/formulae/skhd"
# brew "koekeishiya/formulae/yabai"

# Casks
# cask "google-chrome"
cask "iterm2"
cask "raycast"
cask "notion"
cask "whatsapp"
# cask "yakyak"
# cask "mark-text"
# cask "alacritty"
# cask "docker"
cask "firefox"
# cask "zoom"
# cask "slack"
cask "font-hack"
cask "font-hack-nerd-font"
cask "font-fira-code-nerd-font"
cask "font-fira-mono-nerd-font"
# cask "spotify"
cask "the-unarchiver"
cask "visual-studio-code"
# cask "mediaelch"
# cask "iina"
# cask "disk-inventory-x"

